src/main/java/com/bean/Pager.java
package com.bean;

public class Pager {
    private int displayPerPage = 10;
    private int currentPage = 1;
    private int totalResult = 0;
    private String orderColumn = "";
    private String keyword = null;
    private boolean asc = true;

    public Pager() {
    }

    public int getDisplayPerPage() {
        return displayPerPage;
    }

    public void setDisplayPerPage(int displayPerPage) {
        this.displayPerPage = displayPerPage;
    }

    public int getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(int currentPage) {
        this.currentPage = currentPage;
    }

    public int getTotalResult() {
        return totalResult;
    }

    public void setTotalResult(Integer totalResult) {
        this.totalResult = totalResult;
    }

    public boolean getAsc() {
        return asc;
    }

    public void setAsc(boolean asc) {
        this.asc = asc;
    }

    public String getOrderColumn() {
        return orderColumn;
    }

    public void setOrderColumn(String orderColumn) {
        this.orderColumn = orderColumn;
    }

    public int getTotalPage() {
        return totalResult % displayPerPage > 0 ? totalResult / displayPerPage + 1 : totalResult / displayPerPage;
    }    

    public int getFirstResult() {
        return (currentPage - 1) * displayPerPage;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}

src/main/java/com/entity/HistoryAward.java
package com.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "HistoryAward")
public class HistoryAward implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", insertable = false, updatable = false)
    private int id;

    @Column(name = "Name", insertable = false, updatable = false)
    private String name;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", insertable = false, updatable = false)
    private Date createdDate;

    @Column(name = "Amount", insertable = false, updatable = false)
    private BigDecimal amount;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CustomerID", updatable = false, insertable = false)
    private Customer customerID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PartnerID", updatable = false, insertable = false)
    private Customer partnerID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CheckAwardID", updatable = false, insertable = false)
    private CheckAward checkAwardID;

    @Column(name = "IsDeleted", insertable = false, updatable = false)
    private boolean isDeleted;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CircleMumber", updatable = false, insertable = false)
    private CircleWithdraw circleWithdrawID;
    
    @Column(name = "IsAvailability", insertable = false, updatable = false)
    private Boolean isAvailability;

    public HistoryAward() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Customer getCustomerID() {
        return customerID;
    }

    public void setCustomerID(Customer customerID) {
        this.customerID = customerID;
    }

    public Customer getPartnerID() {
        return partnerID;
    }

    public void setPartnerID(Customer partnerID) {
        this.partnerID = partnerID;
    }

    public CheckAward getCheckAwardID() {
        return checkAwardID;
    }

    public void setCheckAwardID(CheckAward checkAwardID) {
        this.checkAwardID = checkAwardID;
    }

    public boolean isIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public CircleWithdraw getCircleWithdrawID() {
        return circleWithdrawID;
    }

    public void setCircleWithdrawID(CircleWithdraw circleWithdrawID) {
        this.circleWithdrawID = circleWithdrawID;
    }

    public Boolean getIsAvailability() {
        return isAvailability;
    }

    public void setIsAvailability(Boolean isAvailability) {
        this.isAvailability = isAvailability;
    }    

}

src/main/java/com/entity/SystemNews.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "SystemNews")
public class SystemNews implements Serializable {

    private Integer id;
    private String title;
    private String shortDescription;
    private String urlAvatar;
    private String content;
    private Boolean isShow;
    private Boolean isDeleted;
    private Date createdDate;
    private Customer customerID;
    private Admin createdAdminID;

    public SystemNews(Integer id) {
        this.id = id;
    }

    public SystemNews() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", insertable = false, updatable = false)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "ShortDescription")
    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }    

    @Column(name = "UrlAvatar")
    public String getUrlAvatar() {
        return urlAvatar;
    }

    public void setUrlAvatar(String urlAvatar) {
        this.urlAvatar = urlAvatar;
    }    

    @Column(name = "Content")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "IsShow")
    public Boolean getIsShow() {
        return isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    @Column(name = "IsDeleted", insertable = false)
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedDate", insertable = false, updatable = false)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CustomerID")
    public Customer getCustomerID() {
        return customerID;
    }

    public void setCustomerID(Customer customerID) {
        this.customerID = customerID;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CreatedAdminID")
    public Admin getCreatedAdminID() {
        return createdAdminID;
    }

    public void setCreatedAdminID(Admin createdAdminID) {
        this.createdAdminID = createdAdminID;
    }

}

src/main/java/com/controller/user/DashboardController.java
package com.controller.user;

import com.bean.Pager;
import com.bean.PagerPlus;
import com.entity.Customer;
import com.facade.CustomerFacade;
import com.facade.HistoryAwardFacade;
import com.facade.HistoryChangeRankFacade;
import com.facade.HistoryPaymentFacade;
import java.util.Calendar;
import java.util.Map;
import javax.servlet.http.HttpSession;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping("/Dashboard")
public class DashboardController {

    @RequestMapping(value = {""}, method = RequestMethod.GET)
    public String Dashboard(HttpSession session, ModelMap mm) {
        Map memberSession = (Map) session.getAttribute("MEMBER_DATA");
        Customer cus = (Customer) memberSession.get("MEMBER");
        Calendar c = Calendar.getInstance();
        mm.put("HOUR", c.get(Calendar.HOUR_OF_DAY));
        mm.put("MINUTE", c.get(Calendar.MINUTE));
        mm.put("SECOND", c.get(Calendar.SECOND));
        CustomerFacade cF = new CustomerFacade();
        PagerPlus pager = new PagerPlus();
        pager.setIsCheck(1);
        pager.setOrderColumn("createdDate");
        pager.setAsc(false);
        pager.setDisplayPerPage(5);
        Pager pagerChangeRank = new Pager();
        pagerChangeRank.setOrderColumn("createdDate");
        pagerChangeRank.setAsc(false);
        pagerChangeRank.setDisplayPerPage(5);
        mm.put("HISTORY_PAYMENT", new HistoryPaymentFacade().pager(pager, cus.getId()));
        mm.put("AWARD_CHART_DATA", new HistoryAwardFacade().getAwardChartData(cus.getId()));
        mm.put("HISTORY_CHANGE_RANK", new HistoryChangeRankFacade().pager(pagerChangeRank, cus.getId()));
        mm.put("BASIC_INFOMATION", cF.getBasicInfomation(cus.getId()));
        mm.put("TOP5_CHILDREN", cF.getTop5Children(cus.getId()));
        return "MemberDashboard";
    }
}

src/main/java/com/controller/user/SystemController.java
package com.controller.user;

import com.bean.PagerPlus;
import com.entity.Customer;
import com.facade.CustomerFacade;
import com.utils.CustomFunction;
import java.util.Map;
import javax.servlet.http.HttpSession;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping("")
public class SystemController {

    @RequestMapping(value = "/System", method = RequestMethod.GET)
    public String System(HttpSession session, ModelMap mm) {
        Map memberSession = (Map) session.getAttribute("MEMBER_DATA");
        Customer cus = (Customer) memberSession.get("MEMBER");
        String tree = CustomFunction.buildTreeCustomer(new CustomerFacade().getTreeCustomer(cus.getId(), 3), cus.getParentID() == null ? null : cus.getParentID().getId(), "/System");
        mm.put("TREE_CUSTOMER", tree);
        return "MemberSystem";
    }

    @RequestMapping(value = "/System/Next/{id}/{fisrtId}", method = RequestMethod.GET,
            produces = "text/plain;charset=UTF-8")
    @ResponseBody
    public String nextTreeCustomerView(@PathVariable(value = "id") Integer id, @PathVariable(value = "fisrtId") Integer fisrtId) {
        String tree = CustomFunction.buildTreeCustomer(new CustomerFacade().getTreeCustomer(id, 3), fisrtId, "/System");
        return tree;
    }

    @RequestMapping(value = {"/Referral"}, method = RequestMethod.GET)
    public ModelAndView Referral(@RequestParam(value = "currentPage", required = false, defaultValue = "1") int currentPage,
            @RequestParam(value = "keyword", required = false) String keyword,
            @RequestParam(value = "level", required = false) Integer level, HttpSession session) {
        Map memberSession = (Map) session.getAttribute("MEMBER_DATA");
        Customer member = (Customer) memberSession.get("MEMBER");
        ModelMap mm = new ModelMap();
        PagerPlus pager = new PagerPlus();
        pager.setCurrentPage(currentPage);
        pager.setDisplayPerPage(10);
        pager.setAsc(false);
        pager.setOrderColumn("rankCustomer");
        pager.setKeyword(keyword);
        pager.setIsCheck(level);
        mm.put("RESULTS", new CustomerFacade().pagerReferral(pager, member));
        mm.put("PAGER", pager);
        return new ModelAndView("MemberReferral", mm);
    }
}

src/main/java/com/controller/user/SystemNewsController.java
package com.controller.user;

import com.bean.Pager;
import com.entity.Customer;
import com.facade.SystemNewsFacade;
import java.util.Map;
import javax.servlet.http.HttpSession;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping("")
public class SystemNewsController {

    @RequestMapping(value = {"/SystemNews"}, method = RequestMethod.GET)
    public ModelAndView Referral(@RequestParam(value = "currentPage", required = false, defaultValue = "1") int currentPage,
            @RequestParam(value = "keyword", required = false) String keyword, HttpSession session) {
        Map memberSession = (Map) session.getAttribute("MEMBER_DATA");
        Customer member = (Customer) memberSession.get("MEMBER");
        ModelMap mm = new ModelMap();
        Pager pager = new Pager();
        pager.setCurrentPage(currentPage);
        pager.setDisplayPerPage(10);
        pager.setAsc(false);
        pager.setOrderColumn("createdDate");
        pager.setKeyword(keyword);
        mm.put("RESULTS", new SystemNewsFacade().pager(pager, member));
        mm.put("PAGER", pager);
        return new ModelAndView("MemberSystemNews", mm);
    }

    @RequestMapping(value = {"/SystemNews/{id}"}, method = RequestMethod.GET)
    public ModelAndView Referral(@PathVariable(value = "id") int id, ModelMap mm, HttpSession session) {
        mm.put("SELECTED_NEWS", new SystemNewsFacade().find(id));
        return new ModelAndView("MemberSystemNewsDetail", mm);
    }
}

src/main/webapp/Views/Member/Content/referral.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="f" uri="/WEB-INF/tlds/functions.tld" %>
<link href="<c:url value="/Resources/layout/member/css/system.css"/>" rel="stylesheet" type="text/css"/>
<h1>Danh sách nhánh dưới</h1>
<div class="history-trading">
    <div class="row">
        <div class="col-12 col-sm-4">
            <div class="group text-center text-uppercase">
                Bộ lọc
            </div><br/>
            <form action="/Referral" method="GET" novalidate>
                <div class="form-group">
                    <label for="keyword">Từ khóa</label>
                    <input type="text" class="form-control" value="${PAGER.keyword}" name="keyword" id="keyword" placeholder="Họ tên hoặc tên đăng nhập">
                </div>
                <div class="form-group">
                    <label for="isCheck">Level tuyến dưới</label>
                    <input type="number" min="1" step="1" value="${PAGER.isCheck}" class="form-control" name="level" id="isCheck" placeholder="Đời F mấy. VD: F1, F2, F3...">
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-danger text-uppercase">&emsp;Tìm&emsp;</button>
                </div>
            </form>
        </div>
        <div class="col-12 col-sm-8">
            <div class="group text-right">
                Tổng thành viên: <b class="text-danger">${PAGER.totalResult} Thành Viên</b>
            </div>
            <c:forEach items="${RESULTS}" var="item">
                <div class="item">
                    <div class="row no-gutters">
                        <div class="col-3">
                            <div class="top">
                                ${f:customFormatDate("dd/MM/yyyy",item.createdDate)}
                            </div>
                            <div class="bottom">                        
                                ${f:customFormatDate("HH:mm:ss",item.createdDate)}
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="top">
                                <span class="text-info text-uppercase">Nhánh F${item.level-MEMBER.level}</span>
                            </div>
                            <div class="bottom text-uppercase">
                                Người dùng: <b>${item.userName}</b>
                            </div>
                        </div>
                        <div class="col-5 text-right">
                            <div class="top">&nbsp;</div>
                            <div class="bottom text-uppercase">
                                <c:choose>
                                    <c:when test="${child.rankCustomer==1}">
                                        <span class="badge badge-success">Đại lý</span>
                                    </c:when>
                                    <c:when test="${child.rankCustomer==2}">
                                        <span class="badge badge-warning">Đại lý khu vực</span>
                                    </c:when>
                                    <c:when test="${child.rankCustomer==3}">
                                        <span class="badge badge-info">Đại lý vùng</span>
                                    </c:when>
                                    <c:when test="${child.rankCustomer==4}">
                                        <span class="badge badge-danger">Tổng đại lý</span>
                                    </c:when>
                                    <c:otherwise>
                                        <span class="badge badge-dark">Thành viên mới</span>
                                    </c:otherwise>
                                </c:choose>
                            </div>
                        </div>
                    </div>
                </div>
            </c:forEach>
            <br/>
            <c:if test="${PAGER.totalResult>0}">
                <div class="d-flex justify-content-end">
                    <ul class="pagination pagination-sm">
                        <li class="${PAGER.currentPage<=1?"d-none":""}">
                            <a href="<c:url value="/Referral?currentPage=1&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-double-left"></i></a>
                        </li>
                        <li class="${PAGER.currentPage<=1?"d-none":""}">
                            <a href="<c:url value="/Referral?currentPage=${PAGER.currentPage-1}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-left"></i></a>
                        </li>
                        <c:if test="${PAGER.currentPage==2}">
                            <li>
                                <a href="<c:url value="/Referral?currentPage=1&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>">1</a>
                            </li>
                        </c:if>
                        <c:if test="${PAGER.currentPage>2}">
                            <c:forEach begin="${PAGER.currentPage-2}" end="${PAGER.currentPage-1}" var="page">
                                <li>
                                    <a href="<c:url value="/Referral?currentPage=${page}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>">${page}</a>
                                </li>
                            </c:forEach>
                        </c:if>
                        <li>
                            <a class="active" href="javascript:;">${PAGER.currentPage}</a>
                        </li>                
                        <c:if test="${PAGER.currentPage==PAGER.totalPage-1}">
                            <li>
                                <a href="<c:url value="/Referral?currentPage=${PAGER.totalPage}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>">${PAGER.totalPage}</a>
                            </li>
                        </c:if>
                        <c:if test="${PAGER.currentPage<PAGER.totalPage-1}">
                            <c:forEach begin="${PAGER.currentPage+1}" end="${PAGER.currentPage+2}" var="page">
                                <li>
                                    <a href="<c:url value="/Referral?currentPage=${page}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>">${page}</a>
                                </li>
                            </c:forEach> 
                        </c:if>              
                        <li class="${PAGER.currentPage==PAGER.totalPage?"d-none":""}">
                            <a href="<c:url value="/Referral?currentPage=${PAGER.currentPage+1}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-right"></i></a>
                        </li>
                        <li class="${PAGER.currentPage==PAGER.totalPage?"d-none":""}">
                            <a href="<c:url value="/Referral?currentPage=${PAGER.totalPage}&isCheck=${PAGER.isCheck}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-double-right"></i></a>
                        </li>
                    </ul>
                </div>
            </c:if>
        </div>
    </div>
</div>

src/main/webapp/Views/Member/Content/system.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="f" uri="/WEB-INF/tlds/functions.tld" %>
<link href="<c:url value="/Resources/layout/member/css/system.css"/>" rel="stylesheet" type="text/css"/>
<h1>Cây hệ thống</h1>
<div id="distributor-view-tree">
    <div id="treeDiagram">
        ${TREE_CUSTOMER}
    </div>
</div>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover({
            container: 'body',
            html: true,
            trigger: "hover"
        });
    });
    $(document).on('click touchstart', '#treeDiagram span[class|="ti"]', function () {
        $(this).toggleClass('ti-plus').toggleClass('ti-minus');
        $(this).parent().next('ul').toggle(0);
        var target = $(this).parents('.next-item');
        $(target).removeClass('next-item');
        var controller = $(this).attr('controller');
        sendAjax(controller, 'GET', null, function (data) {
            $(target).append(data);
            $('[data-toggle="popover"]').popover({
                container: 'body',
                html: true,
                trigger: "hover"
            });
        });
    });
    function sendAjax(url, type, data, handle) {
        $.ajax({
            url: url,
            type: type,
            data: data,
            success: function (data) {
                if (typeof handle !== "undefined") {
                    handle(data);
                }
            }
        });
    }
</script>

src/main/webapp/Views/Member/Content/systemnews.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="f" uri="/WEB-INF/tlds/functions.tld" %>
<link href="<c:url value="/Resources/layout/member/css/system.css"/>" rel="stylesheet" type="text/css"/>
<h1>Tin nội bộ</h1>
<div class="history-trading">

    <form action="/SystemNews" method="GET" novalidate>
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" value="${PAGER.keyword}" name="keyword" id="keyword" placeholder="Từ khóa">
                <div class="input-group-append">
                    <button class="btn btn-dark" type="button" id="button-addon2">Tìm kiếm</button>
                </div>
            </div>
        </div>
    </form>
    <div class="group text-right">
        Tổng bài đăng: <b class="text-danger">${PAGER.totalResult} bài</b>
    </div>
    <c:forEach items="${RESULTS}" var="item">
        <div class="item">
            <div class="bottom text-uppercase">
                <b class="text-info text-uppercase"><a href="/SystemNews/${item.id}">${item.title}</a></b>
            </div>
            <div class="top text-primary mt-1 mb-1">
                <i class="far fa-calendar-alt"></i> Ngày đăng: ${f:customFormatDate("dd/MM/yyyy", item.createdDate)}
            </div>
            <div class="bottom">
                ${item.shortDescription}
            </div>
        </div>
        <hr/>
    </c:forEach>
    <br/>
    <c:if test="${PAGER.totalPage>1}">
        <div class="d-flex justify-content-end">
            <ul class="pagination pagination-sm">
                <li class="${PAGER.currentPage<=1?"d-none":""}">
                    <a href="<c:url value="/Referral?currentPage=1&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-double-left"></i></a>
                </li>
                <li class="${PAGER.currentPage<=1?"d-none":""}">
                    <a href="<c:url value="/Referral?currentPage=${PAGER.currentPage-1}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-left"></i></a>
                </li>
                <c:if test="${PAGER.currentPage==2}">
                    <li>
                        <a href="<c:url value="/Referral?currentPage=1&keyword=${PAGER.keyword}"/>">1</a>
                    </li>
                </c:if>
                <c:if test="${PAGER.currentPage>2}">
                    <c:forEach begin="${PAGER.currentPage-2}" end="${PAGER.currentPage-1}" var="page">
                        <li>
                            <a href="<c:url value="/Referral?currentPage=${page}&keyword=${PAGER.keyword}"/>">${page}</a>
                        </li>
                    </c:forEach>
                </c:if>
                <li>
                    <a class="active" href="javascript:;">${PAGER.currentPage}</a>
                </li>                
                <c:if test="${PAGER.currentPage==PAGER.totalPage-1}">
                    <li>
                        <a href="<c:url value="/Referral?currentPage=${PAGER.totalPage}&keyword=${PAGER.keyword}"/>">${PAGER.totalPage}</a>
                    </li>
                </c:if>
                <c:if test="${PAGER.currentPage<PAGER.totalPage-1}">
                    <c:forEach begin="${PAGER.currentPage+1}" end="${PAGER.currentPage+2}" var="page">
                        <li>
                            <a href="<c:url value="/Referral?currentPage=${page}&keyword=${PAGER.keyword}"/>">${page}</a>
                        </li>
                    </c:forEach> 
                </c:if>              
                <li class="${PAGER.currentPage==PAGER.totalPage?"d-none":""}">
                    <a href="<c:url value="/Referral?currentPage=${PAGER.currentPage+1}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-right"></i></a>
                </li>
                <li class="${PAGER.currentPage==PAGER.totalPage?"d-none":""}">
                    <a href="<c:url value="/Referral?currentPage=${PAGER.totalPage}&keyword=${PAGER.keyword}"/>"><i class="fa fa-angle-double-right"></i></a>
                </li>
            </ul>
        </div>
    </c:if>
</div>

src/main/webapp/Views/Member/Content/systemnewsdetail.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="f" uri="/WEB-INF/tlds/functions.tld" %>
<link href="<c:url value="/Resources/layout/member/css/system.css"/>" rel="stylesheet" type="text/css"/>
<h1>${SELECTED_NEWS.title}</h1>
<div class="history-trading">
    <div class="item mb-3">
        <div class="bottom">
            <b class="text-info"><i class="far fa-calendar-alt"></i> Ngày đăng: ${f:customFormatDate("dd/MM/yyyy", SELECTED_NEWS.createdDate)}</b>
        </div>
    </div>
    <div class="item mb-3">
        <div class="bottom text-wrap">
            ${SELECTED_NEWS.content}
        </div>
    </div>
    <div class="item">
        <div class="bottom text-right">
            <a href="/SystemNews"><i class="fas fa-arrow-left"></i> Quay lại</a>
        </div>
    </div>
</div>